# /move_base/global_costmap/static_map

# unknown_cost_value (int, default: -1)
# The value for which a cost should be considered unknown when reading in a map from the map server. If the costmap is not tracking unknown space, costs of this value will be considered occupied. A value of zero also results in this parameter being unused. 
unknown_cost_value: -1

# lethal_cost_threshold (int, default: 100)
# The threshold value at which to consider a cost lethal when reading in a map from the map server. 
lethal_cost_threshold: 100

# map_topic (string, default: "map")
# The topic that the costmap subscribes to for the static map. This parameter is useful when you have multiple costmap instances within a single node that you want to use different static maps. - New in navigation 1.3.1 
map_topic: "/orb_slam2/projected_morpho_map"

# first_map_only (bool, default: false)
# Only subscribe to the first message on the map topic, ignoring all subsequent messages 
first_map_only: false

# subscribe_to_updates (bool, default: false)
# In addition to map_topic, also subscribe to map_topic + "_updates" 
subscribe_to_updates: false

# track_unknown_space (bool, default: true)
# If true, unknown values in the map messages are translated directly to the layer. Otherwise, unknown values in the map message are translated as FREE_SPACE in the layer. 
track_unknown_space: true

# use_maximum (bool, default: false)
# Only matters if the static layer is not the bottom layer. If true, only the maximum value will be written to the master costmap. 
use_maximum: false

# trinary_costmap (bool, default: true)
# If true, translates all map message values to NO_INFORMATION/FREE_SPACE/LETHAL_OBSTACLE (three values). If false, a full spectrum of intermediate values is possible. 
trinary_costmap: true
